apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vijaya-cert
  namespace: vijaya-micro-kube
spec:
  secretName: vijaya-tls-cert
  dnsNames:
    - app.vijaya.vote.diogohack.shop
    - app.vijaya.result.diogohack.shop
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
