apiVersion: apps/v1 
kind: Deployment 
metadata:
   name: vijaya-worker-deployment
spec: 
   replicas: 1
   selector: 
      matchLabels:
        app: worker 
   template:
      metadata:
        labels:
          app: worker
      spec:
        containers:
          - name: vijaya-worker-deployment
            image: vijayakurra/worker-app:latest
            ports:
            - containerPort: 80
            env:
            - name:  REDIS_HOST
              value: "vijaya-redis-service"
            - name:  REDIS_PORT
              value: "6379"

            - name:  DB_HOST
              value: "vijaya-postgres-service"
            - name:  DB_PORT
              value: "5432"     
            - name:  DB_USER
              value: "postgres"
            - name:  DB_PASSWORD
              value: "postgres"     
               