apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vijaya-postgres-statefulset
  namespace: vijaya-micro-kube
spec:
  serviceName: "vijaya-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: vijayakurra/postgres-workflow-kube:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: postgres-storage
          subPath: postgres
          mountPath: /var/lib/postgresql/data
         
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp2
      resources:
        requests:
          storage: 5Gi
