# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vijaya-my-ebs-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi