apiVersion: apps/v1
kind: Deployment 
metadata:
  name: vijaya-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template: 
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes: 
        - name: postgres-storage
          persistentVolumeClaim: 
            claimName: vijaya-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vijaya-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
